export const users = [
  {
    id: 1,
    firstName: 'Alice',
    lastName: 'Smith',
    birthDate: '1990-05-15',
    numOfSkills: 5,
    hobbies: ['Reading', 'Photography', 'Yoga'],
  },
  {
    id: 2,
    firstName: 'Bob',
    lastName: 'Johnson',
    birthDate: '1985-09-22',
    numOfSkills: 3,
    hobbies: ['Cooking', 'Hiking'],
  },
  {
    id: 3,
    firstName: 'Charlie',
    lastName: 'Brown',
    birthDate: '1993-02-08',
    numOfSkills: 7,
    hobbies: ['Gardening', 'Painting', 'Traveling'],
  },
  {
    id: 4,
    firstName: 'David',
    lastName: 'Miller',
    birthDate: '1988-11-14',
    numOfSkills: 4,
    hobbies: ['Cycling', 'Playing Guitar'],
  },
  {
    id: 5,
    firstName: 'Emily',
    lastName: 'Jones',
    birthDate: '1995-07-30',
    numOfSkills: 6,
    hobbies: ['Singing', 'Chess'],
  },
  {
    id: 6,
    firstName: 'Frank',
    lastName: 'Wilson',
    birthDate: '1982-04-19',
    numOfSkills: 2,
    hobbies: ['Photography', 'Cooking'],
  },
  {
    id: 7,
    firstName: 'Grace',
    lastName: 'Davis',
    birthDate: '1991-08-03',
    numOfSkills: 8,
    hobbies: ['Reading', 'Running', 'Painting'],
  },
  {
    id: 8,
    firstName: 'Henry',
    lastName: 'Martinez',
    birthDate: '1987-12-27',
    numOfSkills: 5,
    hobbies: ['Traveling', 'Playing Piano'],
  },
  {
    id: 9,
    firstName: 'Ivy',
    lastName: 'Brown',
    birthDate: '1994-06-10',
    numOfSkills: 3,
    hobbies: ['Cycling'],
  },
  {
    id: 10,
    firstName: 'Jack',
    lastName: 'Anderson',
    birthDate: '1980-09-18',
    numOfSkills: 6,
    hobbies: ['Skiing', 'Reading'],
  },
  {
    id: 11,
    firstName: 'Karen',
    lastName: 'Clark',
    birthDate: '1999-01-25',
    numOfSkills: 4,
    hobbies: ['Playing Guitar', 'Cooking'],
  },
  {
    id: 12,
    firstName: 'Leo',
    lastName: 'Garcia',
    birthDate: '1983-03-07',
    numOfSkills: 7,
    hobbies: ['Photography', 'Hiking'],
  },
  {
    id: 13,
    firstName: 'Mia',
    lastName: 'White',
    birthDate: '1996-12-12',
    numOfSkills: 5,
    hobbies: ['Painting', 'Reading'],
  },
]
